#!/bin/bash

sxhkd -c ~/.config/sxhkd/common ~/.config/sxhkd/swm &
feh --bg-fill ~/Pictures/wall.jpg &
setxkbmap -layout us,cz -variant ,qwerty
xsetroot -cursor_name left_ptr
xdotool set_desktop 0
xdotool set_num_desktops 9
redshift &
picom &

mons -m #mirror
#mons -e top #secondary above primary

swmctl debug /tmp/swm.log

swmctl group names 1 2 3 4 5 6 7 8 9

swmctl config border 1 888888 BBC5FF F44336

swmctl config move-drag-shortcut Mod4-1
swmctl config resize-drag-shortcut Mod4-3

swmctl group mode auto

swmctl config font "/usr/share/fonts/TTF/JetBrainsMono-Bold.ttf"
swmctl config info-bg-color FF00BCD4
swmctl config info-text-color FFFFFFFF

# AUTOSTART
spotify &
termite -e fish --class="DESKTOP=0" &
termite -e fish --class="DESKTOP=0" &
termite -e fish --class="DESKTOP=7" &

.config/polybar/launch.sh &
