add_newline = false

format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $memory_usage\
    $character\
    """

[directory]
style = "bold #8787af"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #5f87af"

[git_commit]
style = "bold #5f87af"

[git_state]
style = "bold #5f87af"

[git_status]
style = "bold #d75f87"
stashed = ""

[memory_usage]
disabled = false
show_percentage = true
threshold = 70
symbol = " "
style = "bold #8787af"

[character]
success_symbol = "[❯](bold #8787af)"
error_symbol = "[❯](bold red)"
