add_newline = false

format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $character\
    """

[directory]
style = "bold #bd93f9"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #ff79c6"

[git_commit]
style = "bold #ff79c6"

[git_state]
style = "bold #ff79c6"

[git_status]
style = "bold #f1fa8c"
stashed = ""

