#! /bin/sh

sxhkd -c ~/.config/sxhkd/common ~/.config/sxhkd/bspwm &
feh --bg-fill ~/Pictures/wall.jpg &
setxkbmap -layout us,cz -variant ,qwerty
xsetroot -cursor_name left_ptr
redshift &
picom &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#888888"
bspc config active_border_color "#BBC5FF"
bspc config focused_border_color "#BBC5FF"


